trigger:
- master


pool:
       name: Default
       demands: mycap

stages:
  - stage: Welcome
    jobs:
    - job: PrintMessage
     
      steps:
        - script: echo 'Hello To User!!!'
    - job: AssignTask
     
      steps:
        - script: echo 'Different Tasks are Building ,testing and Packaging'