trigger:
- master

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
         name: Default
         demands: mycap
        steps:
        
        - script: echo 'Building application'
  - stage: Test
    jobs:
       - job: Test
         pool:
          name: Default
          demands: mycap1
         steps:
           - script: echo 'Testing application'
  