trigger:
- master

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
         name: Defult
         demands: mycap
        steps:
        - task: VSBuild@1
        - script: echo 'Building application'
  - stage: Test
    jobs:
       - job: Test
         pool:
          name: Default
          demands: mycap1]
         steps:
           - task: VSTest@2
           - script: echo 'Testing application'
  - stage: Package
    jobs:
       - job: Package
         pool:
          name: Default
          demands: mycap
         steps:
         - script: echo 'Packaging application' 
    